from pathlib import Path

from parser import parse_routes, load_json_file

PATH = Path(__file__).resolve().parent.parent.parent
FILE_PATH = PATH / "generated" / "routes.rs"

ALLOWED_HTTP_METHODS = {"GET", "POST"}
ALLOWED_DB_METHODS = {
    "GET_LAST_MODIFIED",
    "SET_LAST_MODIFIED",
    "GET_TOPICS",
    "ADD_TOPICS",
}

HTTP_PREFIX_MAP = {
    "GET": "async fn get_",
    "POST": "async fn post_",
}

DB_METHOD_MAP = {
    "GET_TOPICS": "Json(db.get_topics().await.unwrap())",
    "GET_LAST_MODIFIED": "Json(db.get_last_modified().await.unwrap())",
    "SET_LAST_MODIFIED": "db.set_last_modified().await.unwrap();",
    "ADD_TOPICS": "db.add_topics().await.unwrap();",
}

def function_name_gen(routes):
    generated_functions = []

    for parameter in routes:
        if parameter.method not in ALLOWED_HTTP_METHODS:
            raise ValueError(f"Invalid HTTP method: {parameter.method}")
        if parameter.db_method not in ALLOWED_DB_METHODS:
            raise ValueError(f"Invalid DB method: {parameter.db_method}")

        
        method_prefix = HTTP_PREFIX_MAP[parameter.method]
        db_body = DB_METHOD_MAP.get(
            parameter.db_method,
            "// TODO: missing logic for this method"
        )

        fn_code = f"{method_prefix}{parameter.name}() {{\n    {db_body}\n}}"
        generated_functions.append(fn_code)

    return "\n\n".join(generated_functions)
    
def render_rsfile(content):
    """Renders the content to a Rust file."""

    # Generate the parent directory if it doesn't exist
    FILE_PATH.parent.mkdir(parents=True, exist_ok=True)

    with open(FILE_PATH, "w", encoding="utf-8") as f:
        f.write(content)
    

def renderer():
    data = load_json_file()
    routes = parse_routes(data)
    content= f"//Code generated by Omega Generator \n {function_name_gen(routes)}"
    render_rsfile(content)